name: "CI"
on:
    push:
    pull_request:

jobs:
    hack:
        name: cargo hack
        runs-on: ubuntu-latest
        steps:
            - uses: taiki-e/install-action@cargo-hack
            - run: cargo hack check --feature-powerset --no-dev-deps
    test:
        name: cargo test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: cargo test --all-features
    clippy:
        name: cargo clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  components: clippy
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - run: cargo clippy --all-features -- -D warnings
        # check formatting with rustfmt
    rustfmt:
        name: cargo fmt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            # Ensure rustfmt is installed and setup problem matcher
            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  components: rustfmt
            - name: Rustfmt Check
              uses: actions-rust-lang/rustfmt@v1
